[project]
name = "agentscope"
dynamic = ["version"]
description = "AgentScope: A Flexible yet Robust Multi-Agent Platform."
readme = "README.md"

authors = [
    { name = "SysML team of Alibaba Tongyi Lab", email = "gaodawei.gdw@alibaba-inc.com" }
]

license = "Apache-2.0"

requires-python = ">=3.10,<3.13"

dependencies = [
    "aioitertools",
    "anthropic",
    "dashscope",
    "docstring_parser",
    "filetype",
    "json5",
    "json_repair",
    "mcp>=1.13",
    "numpy",
    "openai",
    "python-datauri",
    "opentelemetry-api>=1.36.0",
    "opentelemetry-sdk>=1.36.0",
    "opentelemetry-exporter-otlp>=1.36.0",
    "opentelemetry-semantic-conventions>=0.57b0",
    "python-socketio",
    "shortuuid",
    "tiktoken",
    "sounddevice",
    "sqlalchemy",
    "python-frontmatter",
    "aiofiles",
    "a2a>=0.44",
]


[project.optional-dependencies]

############ A2A ############
a2a = [
    "a2a-sdk",
    "httpx",
    "nacos-sdk-python>=3.0.0",
]

############ Realtime ############
realtime = [
    "websockets>=14.0",
    "scipy",
]

############ Models ############
gemini = ["google-genai"]

ollama = ["ollama>=0.5.4"]

models = [
    "agentscope[ollama]",
    "agentscope[gemini]",
]

############ Tokens ############
tokens = [
    "Pillow",
    "transformers",
    "jinja2",
]

############ Memory ############
redis_memory = ["redis"]

tablestore_memory = [
    "tablestore-for-agent-memory",
    "tablestore",
]

mem0ai = [
    "mem0ai<=1.0.3",
    "packaging",
]

reme = [
    "reme-ai>=0.2.0.3",
]

memory = [
    "agentscope[redis_memory]",
    "agentscope[mem0ai]",
    "agentscope[reme]",
    "agentscope[tablestore_memory]",
]

############ Readers ############
text-reader = ["nltk"]

pdf-reader = [
    "agentscope[text-reader]",
    "pypdf<=6.5.0",
]

docx-reader = [
    "agentscope[text-reader]",
    "python-docx",
]

excel-reader = [
    "agentscope[text-reader]",
    "pandas",
    "openpyxl",
]

ppt-reader = [
    "agentscope[text-reader]",
    "python-pptx",
]

readers = [
    "agentscope[pdf-reader]",
    "agentscope[docx-reader]",
    "agentscope[excel-reader]",
    "agentscope[ppt-reader]",
]

############ Vector DB ############
qdrant = ["qdrant-client==1.15.1"]

milvus = ["pymilvus[milvus_lite]==2.6.2"]

ali_mysql = ["mysql-connector-python"]

mongodb = ["pymongo"]

oceanbase = ["pyobvector>=0.2.0,<0.3.0"]

vdbs = [
    "agentscope[qdrant]",
    "agentscope[milvus]",
    "agentscope[ali_mysql]",
    "agentscope[mongodb]",
    "agentscope[oceanbase]",
]

############ RAG ############
rag = [
    "agentscope[readers]",
    "agentscope[vdbs]",
]

############ Evaluate ############
evaluate = [
    "ray",
]

############ Tuner ############
tuner = [
    "dspy>=3.1.0",
    "datasets>=4.0.0",
    "litellm[proxy]>=1.75.3",
]

tuner-gpu = [
    "trinity-rft>=0.5.0",
    "dspy>=3.1.0",
    "datasets>=4.0.0",
    "litellm[proxy]>=1.75.3",
]

############ Judge（单独拆出来）############
judge = [
    "py-openjudge",
]

############ Full ############
full = [
    "agentscope[a2a]",
    "agentscope[models]",
    "agentscope[tokens]",
    "agentscope[memory]",
    "agentscope[rag]",
    "agentscope[evaluate]",
    "agentscope[realtime]",
]

############ Dev（不再包含 judge）############
dev = [
    "agentscope[full]",

    "pre-commit",
    "pytest",
    "pytest-asyncio",
    "pytest-forked",

    "sphinx-gallery",
    "furo",
    "myst_parser",

    "matplotlib",

    "fakeredis",
    "aiosqlite",
    "greenlet",

    "dspy",
]


[tool.uv]

environments = [
    "sys_platform == 'linux'"
]

conflicts = [
    [
        { extra = "judge" },
        { extra = "tuner-gpu" }
    ],
    [
        { extra = "dev" },
        { extra = "tuner-gpu" }
    ]
]


[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools.dynamic]
version = {attr = "agentscope._version.__version__"}
